# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalculateRdsReservedInstances < Formula
  desc "Calculate the number and price of rds reserved instances"
  homepage "https://github.com/yutachaos/calculate-rds-reserved-instances"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yutachaos/calculate-rds-reserved-instances/releases/download/v0.0.1/calculate-rds-reserved-instances_0.0.1_darwin_arm64.zip"
      sha256 "a9029d92edbc0251c33c1448510e53cf00988c7499af8b383fd63b66f22278d7"

      def install
        bin.install Dir['calculate-rds-reserved-instances']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yutachaos/calculate-rds-reserved-instances/releases/download/v0.0.1/calculate-rds-reserved-instances_0.0.1_darwin_amd64.zip"
      sha256 "c2a912e044348cc033df9e7f039105339d4788e03dae7728717eae77b5f65848"

      def install
        bin.install Dir['calculate-rds-reserved-instances']
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yutachaos/calculate-rds-reserved-instances/releases/download/v0.0.1/calculate-rds-reserved-instances_0.0.1_linux_armv6.zip"
      sha256 "3d915a97b7bf6c4dcd74af39489cdbf2297afc7b92dd396066b1bd9dee4f4ede"

      def install
        bin.install Dir['calculate-rds-reserved-instances']
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yutachaos/calculate-rds-reserved-instances/releases/download/v0.0.1/calculate-rds-reserved-instances_0.0.1_linux_arm64.zip"
      sha256 "2c9cfcf4c34b0bd8469f23935ceb5d37b1400b3c29ae435a72da454403e3207b"

      def install
        bin.install Dir['calculate-rds-reserved-instances']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yutachaos/calculate-rds-reserved-instances/releases/download/v0.0.1/calculate-rds-reserved-instances_0.0.1_linux_amd64.zip"
      sha256 "4bdc0fa890297ef090a2517d24e4c9476c7819ca5b5e1138bd34463e6577a119"

      def install
        bin.install Dir['calculate-rds-reserved-instances']
      end
    end
  end

  test do
    system "#{bin}/calculate-rds-reserved-instances"
  end
end
