# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalculateRdsReservedInstances < Formula
  desc "Calculate the number and price of rds reserved instances"
  homepage "https://github.com/yutachaos/calculate-rds-reserved-instances"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yutachaos/calculate-rds-reserved-instances/releases/download/v0.0.3/calculate-rds-reserved-instances_0.0.3_darwin_arm64.zip"
      sha256 "ee5ad3f89a2ace6545c235e58806e30ef3b7a936a098d38e9605a05774cbfa45"

      def install
        bin.install Dir['calculate-rds-reserved-instances']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yutachaos/calculate-rds-reserved-instances/releases/download/v0.0.3/calculate-rds-reserved-instances_0.0.3_darwin_amd64.zip"
      sha256 "bf5ac4fd904beb737e6fe9c1fb84c819f71390485f33dc32f21bd5d4a020e9cc"

      def install
        bin.install Dir['calculate-rds-reserved-instances']
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yutachaos/calculate-rds-reserved-instances/releases/download/v0.0.3/calculate-rds-reserved-instances_0.0.3_linux_arm64.zip"
      sha256 "f200c0a54a3f8e0fdf3a851c37c3479707225d6908ed76003956f5bf37c3497f"

      def install
        bin.install Dir['calculate-rds-reserved-instances']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yutachaos/calculate-rds-reserved-instances/releases/download/v0.0.3/calculate-rds-reserved-instances_0.0.3_linux_amd64.zip"
      sha256 "294e3bdb9a4df4e7dd87dfa3f6b9b23456869b8c4e966e3b9636422d938db759"

      def install
        bin.install Dir['calculate-rds-reserved-instances']
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yutachaos/calculate-rds-reserved-instances/releases/download/v0.0.3/calculate-rds-reserved-instances_0.0.3_linux_armv6.zip"
      sha256 "0afb2de5c38eeaba654fe9236b2e4ed710ef764dc8212cd0965702ae851cbb49"

      def install
        bin.install Dir['calculate-rds-reserved-instances']
      end
    end
  end

  test do
    system "#{bin}/calculate-rds-reserved-instances"
  end
end
